#ifndef COLLISIONCONSTANTS_H
#define COLLISIONCONSTANTS_H


const float PLAYER_CULL_COLLISION_DISTANCE = 3.f;
const float PLAYER_COLLISION_RADIUS = 0.12f;
const float PLAYER_PUSH_OUT_OF_OBJECT_FORCE = 0.24f;

#endif
