#ifndef COLLISIONCONSTANTS_H
#define COLLISIONCONSTANTS_H


#define PLAYER_CULL_COLLISION_DISTANCE 15.f

#define PLAYER_COLLISION_RADIUS 0.12f
#define PLAYER_COLLISION_HALF_HEIGHT 0.12f

#define PENETRATION_DEPTH_FORCE 1.01f

#endif
